# Generated by Django 5.2.7 on 2025-10-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='is_editors_pick',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
