# Generated by Django 5.2.7 on 2025-10-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articlepage_is_editors_pick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'verbose_name': 'Article Tag', 'verbose_name_plural': 'Article Tags'},
        ),
    ]
