# Generated by Django 5.2.7 on 2025-10-15 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articletag_options'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField(help_text='Paste the YouTube or Vimeo video URL')),
                ('category', models.CharField(blank=True, help_text='Optional: category tag (e.g. Sports, News, Music)', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Optional: thumbnail image for this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
